# Generated by Django 3.1.1 on 2020-10-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('client_address', models.CharField(max_length=250)),
                ('client_name', models.CharField(max_length=50)),
                ('client_age', models.IntegerField(default=0)),
                ('client_illness', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('client_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='board.client')),
            ],
        ),
    ]
