# Generated by Django 3.1.1 on 2020-10-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='id',
        ),
        migrations.AlterField(
            model_name='situation',
            name='client_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='board.client'),
        ),
    ]
