# Generated by Django 3.1.1 on 2020-10-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
